/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.KhachHang_DAO;
import DAO.NhaHang_DAO;
import DTO.KhachHang;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ql_nhahang.QL_NhanHang;
import ql_nhahang.QL_NhapHang;

/**
 *
 * @author tphan
 */
public class QL_KhachHang extends javax.swing.JFrame {

    KhachHang_DAO dao=new KhachHang_DAO();
    NhaHang_DAO exec=new NhaHang_DAO();
    DefaultTableModel tblModel =new DefaultTableModel();
    public void loadData(){
        tblModel.setRowCount(0);
        try {
            ResultSet resultSet =exec.selectData("exec sp_SelectKH");
            while(resultSet.next())
            {
                tblModel.addRow(new String[]{resultSet.getString(1),resultSet.getString(2),resultSet.getString(3)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(QL_KhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public Integer updateSearchedData()
    {
        tblModel.setRowCount(0);
        int count=0;
        try {
            ResultSet resultSet =dao.findKH(txtTimKiem.getText());
            
            while(resultSet.next())
            {
                tblModel.addRow(new String[]{resultSet.getString(1),resultSet.getString(2),resultSet.getString(3)});
                count++;
            }
            return count;
        } catch (SQLException ex) {
            Logger.getLogger(QL_KhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        return count;
    }
    /**
     * Creates new form QL_HoaDOn
     */
    private void refreshForm()
    {
        loadData();
        txtTenKhachHang.requestFocus();
        txtMaKhachHang.setText("");
        txtTenKhachHang.setText("");
        txtSDTKhachHang.setText("");
    }
    public QL_KhachHang() {
        initComponents();
        String[]header={"Mã khách hàng","Tên khách hàng","Số điện thoại"};
        tblModel.setColumnIdentifiers(header);
        tblDSKhachHang.setModel(tblModel);
        loadData();
        txtMaKhachHang.setEnabled(false);
        this.setLocationRelativeTo(null);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongTinKhachHang = new javax.swing.JPanel();
        lblMaKhachHang = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JTextField();
        lblTenKhachHang = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JTextField();
        lblSDTKhachHang = new javax.swing.JLabel();
        txtSDTKhachHang = new javax.swing.JTextField();
        txtTimKiem = new javax.swing.JTextField();
        lblMaKhachHang1 = new javax.swing.JLabel();
        btnTimKhachHang = new javax.swing.JButton();
        btnTaoMaKH = new javax.swing.JButton();
        pnlChucNang = new javax.swing.JPanel();
        btnXoaKhachHang = new javax.swing.JButton();
        btnSuaKhachHang = new javax.swing.JButton();
        btnThemKhachHang = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        pnlDSKhachHang = new javax.swing.JPanel();
        spnDSKhachHang = new javax.swing.JScrollPane();
        tblDSKhachHang = new javax.swing.JTable();
        mebMenu = new javax.swing.JMenuBar();
        MenuTrangChu = new javax.swing.JMenu();
        MenuMatHang = new javax.swing.JMenu();
        menuNhapHang = new javax.swing.JMenuItem();
        menuNhanHang = new javax.swing.JMenuItem();
        MenuHoaDon = new javax.swing.JMenu();
        MenuNhanVien = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlThongTinKhachHang.setBackground(new java.awt.Color(255, 234, 238));
        pnlThongTinKhachHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        lblMaKhachHang.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMaKhachHang.setText("Mã khách hàng:");

        txtMaKhachHang.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblTenKhachHang.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTenKhachHang.setText("Tên khách hàng:");

        txtTenKhachHang.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblSDTKhachHang.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSDTKhachHang.setText("SĐT:");

        txtSDTKhachHang.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtSDTKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSDTKhachHangKeyTyped(evt);
            }
        });

        txtTimKiem.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblMaKhachHang1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMaKhachHang1.setText("Tìm khách hàng:");

        btnTimKhachHang.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        btnTimKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search.png"))); // NOI18N
        btnTimKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKhachHangActionPerformed(evt);
            }
        });

        btnTaoMaKH.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnTaoMaKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        btnTaoMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMaKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThongTinKhachHangLayout = new javax.swing.GroupLayout(pnlThongTinKhachHang);
        pnlThongTinKhachHang.setLayout(pnlThongTinKhachHangLayout);
        pnlThongTinKhachHangLayout.setHorizontalGroup(
            pnlThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinKhachHangLayout.createSequentialGroup()
                        .addComponent(lblMaKhachHang1)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinKhachHangLayout.createSequentialGroup()
                        .addComponent(lblMaKhachHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlThongTinKhachHangLayout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTimKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlThongTinKhachHangLayout.createSequentialGroup()
                        .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTaoMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lblTenKhachHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSDTKhachHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSDTKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        pnlThongTinKhachHangLayout.setVerticalGroup(
            pnlThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinKhachHangLayout.createSequentialGroup()
                .addComponent(btnTaoMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(pnlThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaKhachHang1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlThongTinKhachHangLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaKhachHang)
                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenKhachHang)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSDTKhachHang)
                    .addComponent(txtSDTKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pnlChucNang.setBackground(new java.awt.Color(255, 234, 238));
        pnlChucNang.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnXoaKhachHang.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnXoaKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete .png"))); // NOI18N
        btnXoaKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKhachHangActionPerformed(evt);
            }
        });

        btnSuaKhachHang.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnSuaKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit.png"))); // NOI18N
        btnSuaKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaKhachHangActionPerformed(evt);
            }
        });

        btnThemKhachHang.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnThemKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/insert.png"))); // NOI18N
        btnThemKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKhachHangActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChucNangLayout = new javax.swing.GroupLayout(pnlChucNang);
        pnlChucNang.setLayout(pnlChucNangLayout);
        pnlChucNangLayout.setHorizontalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoaKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlChucNangLayout.setVerticalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnThemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnXoaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnSuaKhachHang)
                .addGap(39, 39, 39)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pnlDSKhachHang.setBackground(new java.awt.Color(255, 234, 238));
        pnlDSKhachHang.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblDSKhachHang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tblDSKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "SĐT"
            }
        ));
        tblDSKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSKhachHangMouseClicked(evt);
            }
        });
        spnDSKhachHang.setViewportView(tblDSKhachHang);

        javax.swing.GroupLayout pnlDSKhachHangLayout = new javax.swing.GroupLayout(pnlDSKhachHang);
        pnlDSKhachHang.setLayout(pnlDSKhachHangLayout);
        pnlDSKhachHangLayout.setHorizontalGroup(
            pnlDSKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnDSKhachHang, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlDSKhachHangLayout.setVerticalGroup(
            pnlDSKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnDSKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        mebMenu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        MenuTrangChu.setText("Trang chủ");
        MenuTrangChu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MenuTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuTrangChuMouseClicked(evt);
            }
        });
        mebMenu.add(MenuTrangChu);

        MenuMatHang.setText("Mặt Hàng");
        MenuMatHang.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        menuNhapHang.setText("Nhập hàng");
        menuNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhapHangActionPerformed(evt);
            }
        });
        MenuMatHang.add(menuNhapHang);

        menuNhanHang.setText("Nhận hàng");
        menuNhanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhanHangActionPerformed(evt);
            }
        });
        MenuMatHang.add(menuNhanHang);

        mebMenu.add(MenuMatHang);

        MenuHoaDon.setText("Hóa Đơn");
        MenuHoaDon.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MenuHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuHoaDonMouseClicked(evt);
            }
        });
        mebMenu.add(MenuHoaDon);

        MenuNhanVien.setText("Nhân Viên");
        MenuNhanVien.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MenuNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuNhanVienMouseClicked(evt);
            }
        });
        mebMenu.add(MenuNhanVien);

        setJMenuBar(mebMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlThongTinKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDSKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlThongTinKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDSKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Main_QL frmMain = new Main_QL();
        frmMain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnTaoMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMaKHActionPerformed

        txtMaKhachHang.setText(dao.Auto_Increasement_MaKH());
    }//GEN-LAST:event_btnTaoMaKHActionPerformed

    private void txtSDTKhachHangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKhachHangKeyTyped
        // TODO add your handling code here:
        char key=evt.getKeyChar();
        if(!(Character.isDigit(key)|| key==KeyEvent.VK_BACK_SPACE ||key==KeyEvent.VK_DELETE))
        {
         evt.consume();
        }
    }//GEN-LAST:event_txtSDTKhachHangKeyTyped

    private void btnThemKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKhachHangActionPerformed
        // TODO add your handling code here:
        KhachHang khachHang=new KhachHang(txtMaKhachHang.getText(),txtTenKhachHang.getText(),txtSDTKhachHang.getText());
        boolean validate_id=dao.validate_ID(khachHang.getMaKH());
        boolean validate_number=dao.validate_PhoneNumber(khachHang.getSDT(),khachHang.getMaKH());
        if(txtMaKhachHang.getText().isEmpty() ||txtTenKhachHang.getText().isEmpty() ||txtSDTKhachHang.getText().isEmpty())
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đầy đủ thông tin khách hàng!", "Lỗi nhập liệu!",HEIGHT);
        else if(txtSDTKhachHang.getText().length()<10)
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đúng số điện thoại (10-11 số)!", "Lỗi nhập liệu!",HEIGHT);
        else if(validate_number==false)
            JOptionPane.showMessageDialog(this,"Số điện thoại đã tồn tại!", "Lỗi nhập liệu!",HEIGHT);
        else if(validate_id==false)
        {
            int reply = JOptionPane.showConfirmDialog(this, "Mã khách hàng đã tồn tại. Bạn có muốn thay đổi thông tin của khách hàng không?","Xác nhận thay đổi thông tin!", JOptionPane.YES_NO_OPTION);
            if(reply==JOptionPane.YES_OPTION)
            {
                dao.updateKH(khachHang);
                refreshForm();
            }
            else
                refreshForm();
        }
        else
        {
            dao.insertKH(khachHang);
            refreshForm();
        }
    }//GEN-LAST:event_btnThemKhachHangActionPerformed

    
    private void tblDSKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSKhachHangMouseClicked
        // TODO add your handling code here:
        int row=tblDSKhachHang.getSelectedRow();
        txtMaKhachHang.setText((String)tblDSKhachHang.getValueAt(row, 0));
        txtTenKhachHang.setText((String)tblDSKhachHang.getValueAt(row, 1));
        txtSDTKhachHang.setText((String)tblDSKhachHang.getValueAt(row, 2));
    }//GEN-LAST:event_tblDSKhachHangMouseClicked

    private void btnTimKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKhachHangActionPerformed
        // TODO add your handling code here:
        if(txtTimKiem.getText().isEmpty())
            JOptionPane.showMessageDialog(this,"Vui lòng nhập thông tin khách hàng muốn tìm!", "Lỗi nhập liệu!",HEIGHT);
        else
        {
            int count=updateSearchedData();
            if(count==0)
                JOptionPane.showMessageDialog(this,"Không tìm thấy!", "Lỗi tìm kiếm!",HEIGHT);
            else
                JOptionPane.showMessageDialog(this,"Tìm thấy "+count+" kết quả!", "Thành công!",HEIGHT);
        }
    }//GEN-LAST:event_btnTimKhachHangActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnXoaKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKhachHangActionPerformed
        // TODO add your handling code here:
        int[] rows=tblDSKhachHang.getSelectedRows();
        if(rows.length==0)
            JOptionPane.showMessageDialog(this,"Vui lòng chọn ít nhất 1 khách hàng để xóa thông tin!", "Lỗi lựa chọn!",HEIGHT);
        else
        {
            int total=0;
            int reply = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa "+rows.length+" khách hàng vừa chọn không ?","Xác nhận !", JOptionPane.YES_NO_OPTION);
            if(reply==JOptionPane.YES_OPTION)
            {
                for (int i = 0; i < rows.length; i++) {
                if(dao.deleteKH((String)tblDSKhachHang.getValueAt(rows[i], 0))==1)
                    total++;
                }
                if(total==0)
                    JOptionPane.showMessageDialog(this,"Xóa không thành công!", "Không thành công!",JOptionPane.INFORMATION_MESSAGE);
                else
                {
                    JOptionPane.showMessageDialog(this,"Xóa thành công "+total+" khách hàng!", "Thành công!",JOptionPane.INFORMATION_MESSAGE);
                    refreshForm();
                }
            }
            else
                refreshForm();
        }
    }//GEN-LAST:event_btnXoaKhachHangActionPerformed

    private void btnSuaKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaKhachHangActionPerformed
        // TODO add your handling code here:
        KhachHang khachHang=new KhachHang(txtMaKhachHang.getText(),txtTenKhachHang.getText(),txtSDTKhachHang.getText());
        boolean validate_ID=dao.validate_ID(khachHang.getMaKH());
        boolean validate_Number=dao.validate_PhoneNumber(khachHang.getSDT(), khachHang.getMaKH());
        if(txtMaKhachHang.getText().isEmpty() ||txtTenKhachHang.getText().isEmpty() ||txtSDTKhachHang.getText().isEmpty())
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đầy đủ thông tin khách hàng!", "Lỗi nhập liệu!",HEIGHT);
        else if(txtSDTKhachHang.getText().length()<10)
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đúng số điện thoại (10-11 số)!", "Lỗi nhập liệu!",HEIGHT);
        else if(validate_ID==true)
        {
             JOptionPane.showMessageDialog(this,"Mã khách hàng không tồn tại!", "Lỗi nhập liệu!",HEIGHT);
        }
        else if(validate_Number==false)
            JOptionPane.showMessageDialog(this,"Số điện thoại đã tồn tại!", "Lỗi nhập liệu!",HEIGHT);
        else
        {
           dao.updateKH(khachHang);
            refreshForm();
        }
            
    }//GEN-LAST:event_btnSuaKhachHangActionPerformed

    private void MenuNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuNhanVienMouseClicked
        QL_NhanVien qlnv = new QL_NhanVien();
        qlnv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuNhanVienMouseClicked

    private void menuNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhapHangActionPerformed
        QL_NhapHang frm = new QL_NhapHang();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuNhapHangActionPerformed

    private void menuNhanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhanHangActionPerformed
        QL_NhanHang frm = new QL_NhanHang();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuNhanHangActionPerformed

    private void MenuTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuTrangChuMouseClicked
        Main_QL frmMain = new Main_QL();
        frmMain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuTrangChuMouseClicked

    private void MenuHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuHoaDonMouseClicked
        QL_HoaDon qlhd = new QL_HoaDon();
        qlhd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuHoaDonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_KhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuHoaDon;
    private javax.swing.JMenu MenuMatHang;
    private javax.swing.JMenu MenuNhanVien;
    private javax.swing.JMenu MenuTrangChu;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSuaKhachHang;
    private javax.swing.JButton btnTaoMaKH;
    private javax.swing.JButton btnThemKhachHang;
    private javax.swing.JButton btnTimKhachHang;
    private javax.swing.JButton btnXoaKhachHang;
    private javax.swing.JLabel lblMaKhachHang;
    private javax.swing.JLabel lblMaKhachHang1;
    private javax.swing.JLabel lblSDTKhachHang;
    private javax.swing.JLabel lblTenKhachHang;
    private javax.swing.JMenuBar mebMenu;
    private javax.swing.JMenuItem menuNhanHang;
    private javax.swing.JMenuItem menuNhapHang;
    private javax.swing.JPanel pnlChucNang;
    private javax.swing.JPanel pnlDSKhachHang;
    private javax.swing.JPanel pnlThongTinKhachHang;
    private javax.swing.JScrollPane spnDSKhachHang;
    private javax.swing.JTable tblDSKhachHang;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtSDTKhachHang;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
