/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.NhaHang_DAO;
import DAO.NhanVien_DAO;
import DTO.NhanVien;
import DTO.ChucVu;
import java.awt.event.KeyEvent;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ql_nhahang.QL_NhanHang;
import ql_nhahang.QL_NhapHang;

/**
 *
 * @author tphan
 */
public class QL_NhanVien extends javax.swing.JFrame {

    /**
     * Creates new form QL_NhanVien
     */
    NhanVien_DAO dao=new NhanVien_DAO();
    NhaHang_DAO exec=new NhaHang_DAO();
    DefaultTableModel tblModel =new DefaultTableModel();
    public void loadData(){
        tblModel.setRowCount(0);
        try {
            ResultSet resultSet =exec.selectData("exec sp_SelectNV");
            while(resultSet.next())
            {
                tblModel.addRow(new String[]{resultSet.getString(1),resultSet.getString(2),resultSet.getString(3),resultSet.getString(4)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(QL_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     private void refreshForm()
    {
        loadData();
        txtTenNhanVien.requestFocus();
        txtMaNhanVien.setText("");
        txtTenNhanVien.setText("");
        txtSDTNhanVien.setText("");
        loadCBOChucVu("");
    }
    public QL_NhanVien() {
        initComponents();
        String[]header={"Mã nhân viên","Tên nhân viên","Số điện thoại","Chức vụ"};
        tblModel.setColumnIdentifiers(header);
        tblDSNhanVien.setModel(tblModel);
        loadData();
        txtMaNhanVien.setEnabled(false);
        loadCBOChucVu("");
        this.setLocationRelativeTo(null);
    }
    
    private void loadCBOChucVu(String ten)
    {
        cboCVu.removeAllItems();
        int index = 0;
        try {
            ResultSet rs = exec.selectData("SELECT * FROM CHUCVU");
            while (rs.next())
            {
                String maCV = rs.getString("MACV");
                String tenCV = rs.getString("TENCV");
                cboCVu.addItem(new ChucVu(maCV, tenCV));
                if(tenCV.equals(ten))
                    cboCVu.setSelectedIndex(index);
                index++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(QL_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongTinNhanVien = new javax.swing.JPanel();
        lblMaNhanVien = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        lblTenNhanVien = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        lblSDTNhanVien = new javax.swing.JLabel();
        txtSDTNhanVien = new javax.swing.JTextField();
        lblChucVuNhanVien = new javax.swing.JLabel();
        btnTimNhanVien = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnTimNhanVien1 = new javax.swing.JButton();
        cboCVu = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        pnlChucNangNhanVien = new javax.swing.JPanel();
        btnThemNhanVien = new javax.swing.JButton();
        btnXoaNhanVien = new javax.swing.JButton();
        btnSuaNhanVien = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        pnlDSNhanVien = new javax.swing.JPanel();
        spnDSKhachHang = new javax.swing.JScrollPane();
        tblDSNhanVien = new javax.swing.JTable();
        mebMenu = new javax.swing.JMenuBar();
        MenuTrangChu = new javax.swing.JMenu();
        MenuMatHang = new javax.swing.JMenu();
        menuNhapHang = new javax.swing.JMenuItem();
        menuNhanHang = new javax.swing.JMenuItem();
        MenuHoaDon = new javax.swing.JMenu();
        MenuKhachHang = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlThongTinNhanVien.setBackground(new java.awt.Color(255, 234, 238));
        pnlThongTinNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Nhân Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        pnlThongTinNhanVien.setPreferredSize(new java.awt.Dimension(1190, 127));

        lblMaNhanVien.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMaNhanVien.setText("Mã nhân viên:");

        txtMaNhanVien.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblTenNhanVien.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTenNhanVien.setText("Tên nhân viên:");

        txtTenNhanVien.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblSDTNhanVien.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSDTNhanVien.setText("SĐT:");

        txtSDTNhanVien.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtSDTNhanVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSDTNhanVienKeyTyped(evt);
            }
        });

        lblChucVuNhanVien.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblChucVuNhanVien.setText("Chức vụ:");

        btnTimNhanVien.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnTimNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search.png"))); // NOI18N
        btnTimNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimNhanVienActionPerformed(evt);
            }
        });

        txtTimKiem.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btnTimNhanVien1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnTimNhanVien1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        btnTimNhanVien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimNhanVien1ActionPerformed(evt);
            }
        });

        cboCVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Tìm nhân viên:");

        javax.swing.GroupLayout pnlThongTinNhanVienLayout = new javax.swing.GroupLayout(pnlThongTinNhanVien);
        pnlThongTinNhanVien.setLayout(pnlThongTinNhanVienLayout);
        pnlThongTinNhanVienLayout.setHorizontalGroup(
            pnlThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinNhanVienLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlThongTinNhanVienLayout.createSequentialGroup()
                        .addComponent(lblMaNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTenNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSDTNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSDTNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblChucVuNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCVu, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlThongTinNhanVienLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182)))
                .addContainerGap())
        );
        pnlThongTinNhanVienLayout.setVerticalGroup(
            pnlThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinNhanVienLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMaNhanVien)
                        .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSDTNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblChucVuNhanVien)
                        .addComponent(lblSDTNhanVien)
                        .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTenNhanVien)
                        .addComponent(cboCVu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinNhanVienLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnTimNhanVien))
                    .addGroup(pnlThongTinNhanVienLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pnlChucNangNhanVien.setBackground(new java.awt.Color(255, 234, 238));
        pnlChucNangNhanVien.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlChucNangNhanVien.setPreferredSize(new java.awt.Dimension(97, 416));

        btnThemNhanVien.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnThemNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/insert.png"))); // NOI18N
        btnThemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhanVienActionPerformed(evt);
            }
        });

        btnXoaNhanVien.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnXoaNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete .png"))); // NOI18N
        btnXoaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNhanVienActionPerformed(evt);
            }
        });

        btnSuaNhanVien.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnSuaNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit.png"))); // NOI18N
        btnSuaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNhanVienActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
        btnLamMoi.setPreferredSize(new java.awt.Dimension(46, 47));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChucNangNhanVienLayout = new javax.swing.GroupLayout(pnlChucNangNhanVien);
        pnlChucNangNhanVien.setLayout(pnlChucNangNhanVienLayout);
        pnlChucNangNhanVienLayout.setHorizontalGroup(
            pnlChucNangNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChucNangNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThemNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(btnXoaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(btnSuaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        pnlChucNangNhanVienLayout.setVerticalGroup(
            pnlChucNangNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangNhanVienLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnThemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnXoaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnSuaNhanVien)
                .addGap(35, 35, 35)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pnlDSNhanVien.setBackground(new java.awt.Color(255, 234, 238));
        pnlDSNhanVien.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblDSNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tblDSNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Nhân viên", "Tên Nhân viên", "SĐT", "Chức Vụ"
            }
        ));
        tblDSNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSNhanVienMouseClicked(evt);
            }
        });
        spnDSKhachHang.setViewportView(tblDSNhanVien);

        javax.swing.GroupLayout pnlDSNhanVienLayout = new javax.swing.GroupLayout(pnlDSNhanVien);
        pnlDSNhanVien.setLayout(pnlDSNhanVienLayout);
        pnlDSNhanVienLayout.setHorizontalGroup(
            pnlDSNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnDSKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
        );
        pnlDSNhanVienLayout.setVerticalGroup(
            pnlDSNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnDSKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        mebMenu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        MenuTrangChu.setText("Trang chủ");
        MenuTrangChu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MenuTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuTrangChuMouseClicked(evt);
            }
        });
        mebMenu.add(MenuTrangChu);

        MenuMatHang.setText("Mặt hàng");
        MenuMatHang.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        menuNhapHang.setText("Nhập hàng");
        menuNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhapHangActionPerformed(evt);
            }
        });
        MenuMatHang.add(menuNhapHang);

        menuNhanHang.setText("Nhận hàng");
        menuNhanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhanHangActionPerformed(evt);
            }
        });
        MenuMatHang.add(menuNhanHang);

        mebMenu.add(MenuMatHang);

        MenuHoaDon.setText("Hóa Đơn");
        MenuHoaDon.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MenuHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuHoaDonMouseClicked(evt);
            }
        });
        mebMenu.add(MenuHoaDon);

        MenuKhachHang.setText("Khách Hàng");
        MenuKhachHang.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MenuKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuKhachHangMouseClicked(evt);
            }
        });
        mebMenu.add(MenuKhachHang);

        setJMenuBar(mebMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlThongTinNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 1186, Short.MAX_VALUE)
                        .addContainerGap(8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlChucNangNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDSNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlThongTinNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDSNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlChucNangNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuKhachHangMouseClicked
        QL_KhachHang qlkh = new QL_KhachHang();
        qlkh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuKhachHangMouseClicked

    private void btnThemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhanVienActionPerformed
        ChucVu cv = (ChucVu) cboCVu.getSelectedItem();
        NhanVien nhanvien=new NhanVien(txtMaNhanVien.getText(),txtTenNhanVien.getText(),txtSDTNhanVien.getText(),cv.getMaCV());
        boolean validate_maNV=dao.validate_ID(txtMaNhanVien.getText());
        boolean validate_SDT=dao.validate_PhoneNumber(txtSDTNhanVien.getText(), txtMaNhanVien.getText());
        if(txtMaNhanVien.getText().isEmpty()||txtTenNhanVien.getText().isEmpty()||txtSDTNhanVien.getText().isEmpty())
             JOptionPane.showMessageDialog(this,"Vui lòng nhập đầy đủ thông tin nhân viên!", "Lỗi nhập liệu!",HEIGHT);
        else if(txtSDTNhanVien.getText().length()<10)
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đúng số điện thoại (10-11 số)!", "Lỗi nhập liệu!",HEIGHT);
        else if(validate_SDT==false)
            JOptionPane.showMessageDialog(this,"Số điện thoại đã tồn tại!", "Lỗi nhập liệu!",HEIGHT);
        else if(validate_maNV==false)
        {
            int reply = JOptionPane.showConfirmDialog(this, "Mã nhân viên đã tồn tại. Bạn có muốn thay đổi thông tin của nhân viên không?","Xác nhận thay đổi thông tin!", JOptionPane.YES_NO_OPTION);
            if(reply==JOptionPane.YES_OPTION)
            {
                dao.updateNV(nhanvien);
                refreshForm();
            }
            else
                refreshForm();
        }
        else
        {
            dao.insertNV(nhanvien);
            refreshForm();
        }
    }//GEN-LAST:event_btnThemNhanVienActionPerformed
    public Integer updateSearchedData()
    {
        tblModel.setRowCount(0);
        int count=0;
        try {
            ResultSet resultSet =dao.findNV(txtTimKiem.getText());
            
            while(resultSet.next())
            {
                tblModel.addRow(new String[]{resultSet.getString(1),resultSet.getString(2),resultSet.getString(3),resultSet.getString(4)});
                count++;
            }
            return count;
        } catch (SQLException ex) {
            Logger.getLogger(QL_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        return count;
    }
    private void btnTimNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimNhanVienActionPerformed
        // TODO add your handling code here:
        if(txtTimKiem.getText().isEmpty())
            JOptionPane.showMessageDialog(this,"Vui lòng nhập thông tin nhân viên muốn tìm!", "Lỗi nhập liệu!",HEIGHT);
        else
        {
            int count=updateSearchedData();
            if(count==0)
                JOptionPane.showMessageDialog(this,"Không tìm thấy!", "Lỗi tìm kiếm!",HEIGHT);
            else
                JOptionPane.showMessageDialog(this,"Tìm thấy "+count+" kết quả!", "Thành công!",HEIGHT);
        }
    }//GEN-LAST:event_btnTimNhanVienActionPerformed

    private void btnSuaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNhanVienActionPerformed
        ChucVu cv = (ChucVu) cboCVu.getSelectedItem();
         NhanVien nhanVien=new NhanVien(txtMaNhanVien.getText(),txtTenNhanVien.getText(),txtSDTNhanVien.getText(), cv.getMaCV());
        boolean validate_ID=dao.validate_ID(nhanVien.getMaNV());
        boolean validate_Number=dao.validate_PhoneNumber(nhanVien.getSDT(), nhanVien.getMaNV());
        if(txtMaNhanVien.getText().isEmpty()||txtTenNhanVien.getText().isEmpty()||txtSDTNhanVien.getText().isEmpty())
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đầy đủ thông tin nhân viên!", "Lỗi nhập liệu!",HEIGHT);
        else if(txtSDTNhanVien.getText().length()<10)
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đúng số điện thoại (10-11 số)!", "Lỗi nhập liệu!",HEIGHT);
        else if(validate_ID==true)
        {
             JOptionPane.showMessageDialog(this,"Mã nhân viên không tồn tại!", "Lỗi nhập liệu!",HEIGHT);
        }
        else if(validate_Number==false)
            JOptionPane.showMessageDialog(this,"Số điện thoại đã tồn tại!", "Lỗi nhập liệu!",HEIGHT);
        else
        {
           dao.updateNV(nhanVien);
            refreshForm();
        }
    }//GEN-LAST:event_btnSuaNhanVienActionPerformed

    private void btnTimNhanVien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimNhanVien1ActionPerformed
        // TODO add your handling code here:
        txtMaNhanVien.setText(dao.Auto_Increasement_MaNV());
    }//GEN-LAST:event_btnTimNhanVien1ActionPerformed

    private void txtSDTNhanVienKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTNhanVienKeyTyped
        // TODO add your handling code here:
        char key=evt.getKeyChar();
        if(!(Character.isDigit(key)|| key==KeyEvent.VK_BACK_SPACE ||key==KeyEvent.VK_DELETE))
        {
         evt.consume();
        }
    }//GEN-LAST:event_txtSDTNhanVienKeyTyped

    private void tblDSNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSNhanVienMouseClicked
        // TODO add your handling code here:
        int row=tblDSNhanVien.getSelectedRow();
        txtMaNhanVien.setText((String)tblDSNhanVien.getValueAt(row, 0));
        txtTenNhanVien.setText((String)tblDSNhanVien.getValueAt(row, 1));
        txtSDTNhanVien.setText((String)tblDSNhanVien.getValueAt(row, 2));
        String ten = (String)tblDSNhanVien.getValueAt(row, 3);
        loadCBOChucVu(ten);
    }//GEN-LAST:event_tblDSNhanVienMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        refreshForm();
        txtTimKiem.setText("");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNhanVienActionPerformed
        // TODO add your handling code here:
        int[] rows=tblDSNhanVien.getSelectedRows();
        if(rows.length==0)
            JOptionPane.showMessageDialog(this,"Vui lòng chọn ít nhất 1 nhân viên để xóa thông tin!", "Lỗi lựa chọn!",HEIGHT);
        else
        {
            int total=0;
            int reply = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa "+rows.length+" nhân viên vừa chọn không ?","Xác nhận !", JOptionPane.YES_NO_OPTION);
            if(reply==JOptionPane.YES_OPTION)
            {
                for (int i = 0; i < rows.length; i++) {
                if(dao.deleteNV((String)tblDSNhanVien.getValueAt(rows[i], 0))==1)
                    total++;
                }
                if(total==0)
                    JOptionPane.showMessageDialog(this,"Xóa không thành công!", "Không thành công!",JOptionPane.INFORMATION_MESSAGE);
                else
                {
                    JOptionPane.showMessageDialog(this,"Xóa thành công "+total+" nhân viên!", "Thành công!",JOptionPane.INFORMATION_MESSAGE);
                    refreshForm();
                }
            }
            else
                refreshForm();
        }
    }//GEN-LAST:event_btnXoaNhanVienActionPerformed

    private void MenuTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuTrangChuMouseClicked
        Main_QL frmMain = new Main_QL();
        frmMain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuTrangChuMouseClicked

    private void menuNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhapHangActionPerformed
        QL_NhapHang frm = new QL_NhapHang();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuNhapHangActionPerformed

    private void menuNhanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhanHangActionPerformed
         QL_NhanHang frm = new QL_NhanHang();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuNhanHangActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Main_QL frmMain = new Main_QL();
        frmMain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void MenuHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuHoaDonMouseClicked
        QL_HoaDon qlhd = new QL_HoaDon();
        qlhd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuHoaDonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_NhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuHoaDon;
    private javax.swing.JMenu MenuKhachHang;
    private javax.swing.JMenu MenuMatHang;
    private javax.swing.JMenu MenuTrangChu;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSuaNhanVien;
    private javax.swing.JButton btnThemNhanVien;
    private javax.swing.JButton btnTimNhanVien;
    private javax.swing.JButton btnTimNhanVien1;
    private javax.swing.JButton btnXoaNhanVien;
    private javax.swing.JComboBox cboCVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblChucVuNhanVien;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblSDTNhanVien;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JMenuBar mebMenu;
    private javax.swing.JMenuItem menuNhanHang;
    private javax.swing.JMenuItem menuNhapHang;
    private javax.swing.JPanel pnlChucNangNhanVien;
    private javax.swing.JPanel pnlDSNhanVien;
    private javax.swing.JPanel pnlThongTinNhanVien;
    private javax.swing.JScrollPane spnDSKhachHang;
    private javax.swing.JTable tblDSNhanVien;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtSDTNhanVien;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
